require('plugins')
require('keymappings')
require('settings')
require('colorscheme')
require('nv-global')

-- Plugins
require('nv-treesitter')
require('nv-compe')
require('nv-barbar')
require('nv-colorizer')
require('nv-lualine')
require('nv-gitsigns')
require('nv-nvim-autopairs')
require('nv-kommentary')
require('nv-utils')
require('nv-which-key')
require('nv-telescope')
require('nv-dashboard')

-- LSP
require('lsp')
require('lsp.lua-ls')
require('lsp.bash-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
require('lsp.python-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.html-ls')
require('lsp.efm-general-ls')
